### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by danteali** [xcad2k/dotfiles-win#3]
I notice in your terminal json you've referenced some terminal icons, any chance you can add those to the repo too?

**Comment by ChristianLempa** [comment]
No, unfortunately that could cause problems with copy-right. You have to search for your own icons, i'm sorry.

**Comment by soorya-u** [comment]
> I notice in your terminal json you've referenced some terminal icons, any chance you can add those to the repo too?

Hey, Did you find those icons?

**Comment by danteali** [comment]
Don't know if I found the same ones as Christian uses but I just ended up using Google image search to quickly find some icons.
