### ISSUE TITLE
PowerShell without header

### ISSUE THREAD

**Issue by KonerDev** [xcad2k/dotfiles-win#9]
How did you manage that when you open PowerShell this heading doesn't appear:

![image](https://github.com/ChristianLempa/dotfiles-win/assets/105141148/6ed481b8-94c0-495f-af32-eede0dae5fd5)

**Comment by xBen-Harveyx** [comment]
Adding `Clear` to the last line of your [PowerShell profile](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4) should clear all of that text upon start.

**Comment by KonerDev** [comment]
Thanks, I have now found an even better option by simply adding the [`-NoLogo`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-nologo) flag to the startup command in the Windows Terminal Settings under Powershell.
